services:
  bot:
    build: .
    container_name: schedule_bot
    restart: unless-stopped  # Автоматический перезапуск при падении
    environment:
      - BOT_TOKEN=${BOT_TOKEN}           # Токен бота из .env
      - DB_HOST=${DB_HOST}                # Хост БД из .env
      - DB_USER=${DB_USER}                # Пользователь БД из .env
      - DB_PASSWORD=${DB_PASSWORD}        # Пароль БД из .env
      - DB_NAME=${DB_NAME}                # Имя БД из .env
    volumes:
      - .:/app
